name: sensortag
version: "1.0"
summary: SensorTag Python Bluetooth LE implementation
description: API and command line tools for Python Bluetooth Low Energy access
confinement: strict

apps:
  sensortag:
    command: usr/bin/sensortag
    plugs: [home,bluez]
  sensordata:
    command: usr/bin/sensordata
    plugs: [home,bluez]
  sensor:
    command: bin/wrapper
    plugs: [home,bluez]
  sensord:
    command: bin/wrapper
    daemon: simple
    plugs: [home,bluez]
  blescan:
    command: usr/bin/blescan
  # mosquito server
  mosquitto:
    command: usr/sbin/mosquitto -c $SNAP/mosquitto.conf
    daemon: simple
    plugs: [network, network-bind]
  # mosquitto subscriber
  subscribe:
    command: bin/subscribe
    plugs: [network, network-bind]
  rfkill:
    command: usr/sbin/rfkill
  sh:
    command: bin/sh
  ctrl:
    command: usr/bin/bluetoothctl

parts:
  bluepy:
    plugin: python3
    source: https://github.com/liu-xiao-guo/bluepy
    source-type: git
    stage-packages:
      - bluetooth
      - bluez
      - blueman
      #- mosquitto
    build-packages: [libglib2.0-dev, gcc]
    requirements: ./requirements.txt

  rfkill:
    plugin: nil
    stage-packages:
      - rfkill
      
  mosquitto:
    plugin: copy
    stage-packages: [mosquitto]
    files:
      mosquitto.conf: mosquitto.conf

  mqtt-client:
    plugin: copy
    files:
      subscribe.py: bin/subscribe
      ./bin: bin
